direction: right

horizontal-gap: 2

U: Browser
B: "API Gateway\nNginx"

U -> B: HTTP/80

FE: Frontend (HTML only) {
  F: Frontend UI
}

BE: Backend Services (dual listener) {
  H: AUTH Service
  C: Profile Service
  G: Notification Service
  D: Course Catalogue Service
  E: Course Content Service
  J: Assignment Service
}

MQ: Message Queue (async events) {
  Q: "RabbitMQ\nuniversity.events (topic, durable)" {
    shape: cylinder
  }
}


B -> BE: /api/*
B -> FE: everything else

FE -> BE: gRPC-Web {
  style.stroke-dash: 3
}

# Async events til MQ
BE -> MQ: Events {
  style.stroke-dash: 5
}