all: 
	d2 --timeout 300 arch-diagram.d2 -t 0 --layout=elk --pad 0 --elk-algorithm=layered arch-diagram.png 
	d2 --timeout 300 request_id.d2 -t 0 --layout=elk --pad 0 --elk-algorithm=layered request_id.png