syntax = "proto3";

package coursecatalogue;
option go_package = "osbourne.local/course-catalogue-service/coursecatalogue;coursecatalogue";

service CourseCatalogueService {
  rpc GetCourse (GetCourseRequest) returns (GetCourseResponse);
  rpc ListCourses (ListCoursesRequest) returns (ListCoursesResponse);
  rpc EnrollUser (EnrollUserRequest) returns (EnrollUserResponse);
  rpc ListEnrolledCourses (ListEnrolledCoursesRequest) returns (ListEnrolledCoursesResponse);
}

message GetCourseRequest {
  string course_id = 1;
}

message GetCourseResponse {
  Course course = 1;
}

message ListCoursesRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListCoursesResponse {
  repeated Course courses = 1;
  int32 total_count = 2;
}

message EnrollUserRequest {
  string user_id = 1;
  string course_id = 2;
}

message EnrollUserResponse {
  bool success = 1;
}

message ListEnrolledCoursesRequest {
  string user_id = 1;
}

message ListEnrolledCoursesResponse {
  repeated Course enrolled_courses = 1;
}


message Course {
  string id = 1;
  string code = 2;
  string title = 3;
  string description = 4;
  int32 credits = 5;
}
