syntax = "proto3";

package assignment;

import "google/protobuf/timestamp.proto";

option go_package = "osbourne.local/assignment-service/gen/assignment;assignment";

service AssignmentService {
  rpc CreateAssignment(CreateAssignmentRequest) returns (CreateAssignmentResponse);
  rpc GetCourseAssignments(GetCourseAssignmentsRequest) returns (GetCourseAssignmentsResponse);
  rpc GetAssignment(GetAssignmentRequest) returns (GetAssignmentResponse);

  // Submissions (Student and Instructor)
  rpc SubmitAssignment (SubmitAssignmentRequest) returns (SubmitAssignmentResponse);
  // rpc GetSubmission (GetSubmissionRequest) returns (GetSubmissionResponse);
  // rpc ListSubmissions (ListSubmissionsRequest) returns (ListSubmissionsResponse);
  // rpc GradeSubmission (GradeSubmissionRequest) returns (GradeSubmissionResponse);
}

message Assignment {
  string id = 1;
  string course_id = 2;
  string title = 3;
  string description = 4;
  google.protobuf.Timestamp due_date = 5;
}

message CreateAssignmentRequest {
  string course_id = 1;
  string title = 2;
  string description = 3;
  google.protobuf.Timestamp due_date = 4;
}

message CreateAssignmentResponse {
  Assignment assignment = 1;
}

message GetCourseAssignmentsRequest {
  string course_id = 1;
}

message GetCourseAssignmentsResponse {
  repeated Assignment assignments = 1;
}

message GetAssignmentRequest {
  string assignment_id = 1;
}

message GetAssignmentResponse {
  Assignment assignment = 1;
}

message SubmissionMetadata {
  string assignment_id = 1;
  string student_id = 2;
  string filename = 3;
  int64 size = 4;
}

message SubmitAssignmentRequest {
  oneof payload {
    SubmissionMetadata metadata = 1;
    bytes chunk = 2;
  }
}

message SubmitAssignmentResponse {
  string submission_id = 1;
  string file_url = 2;
  string file_name = 3;
  int64 file_size = 4;
}


